/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;


import java.awt.Color;
import java.time.Clock;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;




/**
 *
 * @author Arunalu Hasa
 */
public class SortingInterface extends javax.swing.JFrame {

    /**
     * Creates new form SortingInterface
     */
    public SortingInterface() {
       
       String id1=AlgorithmStimulator.id;
              
       initComponents();
    
       jLabel20.setText(id1);
       jPanel2.setBackground(Color.LIGHT_GRAY);
       jPanel2.setOpaque(true);
       
      
       jLabel10.setBackground(Color.yellow);
       jLabel10.setOpaque(true);
       
       
       jLabel13.setBackground(Color.yellow);
       jLabel13.setOpaque(true);
       
       jLabel12.setBackground(Color.white);
       jLabel12.setOpaque(true);
       
       jLabel15.setBackground(Color.green);
       jLabel15.setOpaque(true);
       
       jLabel0.setText("");
       jLabel1.setText("");
       jLabel2.setText("");
       jLabel3.setText("");
       jLabel4.setText("");
       jLabel5.setText("");
       jLabel6.setText("");
       jLabel7.setText("");
       jLabel8.setText("");
       jLabel9.setText("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel0 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRadioButton1.setText("Ascending Order");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jRadioButton2.setText("Descending Order");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Provide 10 Integer values separate with commas");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Do Sort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel20.setText("jLabel20");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel0.setBackground(new java.awt.Color(204, 255, 204));
        jLabel0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel0.setText("jLabel0");

        jLabel1.setBackground(new java.awt.Color(153, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(102, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(51, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setBackground(new java.awt.Color(0, 255, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel10.setText("12");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel13.setText("15");

        jLabel11.setText("For Comparing adjacent Blocks");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setText("10");

        jLabel14.setText("For Sorted Elements");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel15.setText("28");

        jLabel16.setText("For Elements to be Sorted");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(22, 22, 22)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jRadioButton1)
                                .addGap(57, 57, 57)
                                .addComponent(jRadioButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(175, 175, 175))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String textValue = jTextField1.getText();
        boolean rb1status = jRadioButton1.isSelected();
        boolean rb2status = jRadioButton2.isSelected();
        
        if(rb1status==false && rb2status==false){
            JOptionPane.showMessageDialog(null,"You Have to select an option","Option Selection",JOptionPane.WARNING_MESSAGE);
        }
        if(rb1status){
        
        int count = 0;
        int []array = new int[10];
        StringTokenizer tokenElementSet;
            tokenElementSet = new StringTokenizer( textValue,",");
        try{
        while (tokenElementSet.hasMoreTokens() ){
            try{
            array[count] = Integer.parseInt(tokenElementSet.nextToken());
            }
            catch(NumberFormatException ne){
                JOptionPane.showMessageDialog(null,"Enter Integer Numbers Only",ne.getMessage(),JOptionPane.WARNING_MESSAGE);
                continue;
            }
            System.out.println(array[count]);           
            count++;
            
        }
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"Sorting only for first 10 Numbers you've Entered",e.getMessage(),JOptionPane.WARNING_MESSAGE);
        }
        if(count!=10){
            JOptionPane.showMessageDialog(null,"You Have to Insert 10 Elements","Text Insertion",JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        setLabels(array);
        
        new Thread(new Runnable() {

        @Override
        public void run() {
        int temp;
        
        
        for(int i = 0; i < array.length; i++)
        {
            
            setLabels(array);
            jLabel0.setBackground(Color.yellow);
            jLabel0.setOpaque(true);
            jLabel1.setBackground(Color.yellow);
            jLabel1.setOpaque(true);
            
            try {            
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(SortingInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            for(int j = 1; j < (array.length-i); j++)
            {
            
                try {
                    setLableColourYellow(j);
                    setLableColourGreen(j-1);
                    
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SortingInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                //if array[j-1] > array[j], swap the elements
                if(array[j-1] > array[j])
                {
                    temp = array[j-1];
                    array[j-1]=array[j];
                    array[j]=temp;
                    setLabels(array);
     
                }//if
                setLableColourGreen(j);
                setLableColourWhite(array.length-i);
            }
            try {           
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(SortingInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            jLabel0.setBackground(Color.white);
            jLabel0.setOpaque(true);
            jLabel1.setBackground(Color.white);
            jLabel1.setOpaque(true);
           }
        }).start(); 
        }
       
        }
        else if(rb2status){
            
        int count = 0;
        int []array = new int[10];
        StringTokenizer tokenElementSet;
            tokenElementSet = new StringTokenizer( textValue,",");
        try{
        while (tokenElementSet.hasMoreTokens() ){
            try{
            array[count] = Integer.parseInt(tokenElementSet.nextToken());
            }
            catch(NumberFormatException ne){
                JOptionPane.showMessageDialog(null,"Enter Integer Numbers Only",ne.getMessage(),JOptionPane.WARNING_MESSAGE);
            }
            System.out.println(array[count]);
            
            count++;
        }
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null,"Sorting only for first 10 Numbers you've Entered",e.getMessage(),JOptionPane.WARNING_MESSAGE);
        }
        if(count!=10){
            JOptionPane.showMessageDialog(null,"You Have to Insert 10 Elements","Text Insertion",JOptionPane.WARNING_MESSAGE);
        }
        else{
        
        setLabels(array);
       
        new Thread(new Runnable() {

        @Override
        public void run() {
        int temp;
        
        
        for(int i = 0; i < array.length; i++)
        {
            
            setLabels(array);
            jLabel0.setBackground(Color.yellow);
            jLabel0.setOpaque(true);
            jLabel1.setBackground(Color.yellow);
            jLabel1.setOpaque(true);
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                Logger.getLogger(SortingInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            for(int j = 1; j < (array.length-i); j++)
            {
                try {
                    setLableColourYellow(j);
                    setLableColourGreen(j-1);
                    
                    Thread.sleep(3000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(SortingInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
                //if array[j-1] < array[j], swap the elements
                if(array[j-1] < array[j])
                {
                    temp = array[j-1];
                    array[j-1]=array[j];
                    array[j]=temp;
                    setLabels(array);
                }
                setLableColourGreen(j);
                setLableColourWhite(array.length-i);
                
            }
            try {
            
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(SortingInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jLabel0.setBackground(Color.white);
        jLabel0.setOpaque(true);
        jLabel1.setBackground(Color.white);
        jLabel1.setOpaque(true);
           }
        }).start();
        
        
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AlgorithmStimulator().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortingInterface().setVisible(true);
            }
        });
    }
    public void setLabels(int [] array){
       jLabel0.setText(array[0]+"");
       jLabel1.setText(array[1]+"");
       jLabel2.setText(array[2]+"");
       jLabel3.setText(array[3]+"");
       jLabel4.setText(array[4]+"");
       jLabel5.setText(array[5]+"");
       jLabel6.setText(array[6]+"");
       jLabel7.setText(array[7]+"");
       jLabel8.setText(array[8]+"");
       jLabel9.setText(array[9]+"");
    }
    public void setLableColourGreen(int i){
        
        if(i==1){
            jLabel0.setBackground(Color.green);
            jLabel0.setOpaque(true);
            System.out.println("inside jlable0");
        }
        else if(i==2){
            jLabel1.setBackground(Color.GREEN);
            jLabel1.setOpaque(true);
        }
        else if(i==3){
            jLabel2.setBackground(Color.GREEN);
            jLabel2.setOpaque(true);
        }
        else if(i==4){
            jLabel3.setBackground(Color.GREEN);
            jLabel3.setOpaque(true);
        }
        else if(i==5){
            jLabel4.setBackground(Color.GREEN);
            jLabel4.setOpaque(true);
        }
        else if(i==6){
            jLabel5.setBackground(Color.GREEN);
            jLabel5.setOpaque(true);
        }
        else if(i==7){
            jLabel6.setBackground(Color.GREEN);
            jLabel6.setOpaque(true);
        }
        else if(i==8){
            jLabel7.setBackground(Color.GREEN);
            jLabel7.setOpaque(true);
        }
        else if(i==9){
            jLabel8.setBackground(Color.GREEN);
            jLabel8.setOpaque(true);
        }
        else if(i==10){
            jLabel9.setBackground(Color.GREEN);
            jLabel9.setOpaque(true);
        }
    }
    public void setLableColourYellow(int i){
        
        if(i==1){
            jLabel1.setBackground(Color.yellow);
            jLabel1.setOpaque(true);
            System.out.println("inside jlable0");
        }
        else if(i==2){
            jLabel2.setBackground(Color.yellow);
            jLabel2.setOpaque(true);
        }
        else if(i==3){
            jLabel3.setBackground(Color.yellow);
            jLabel3.setOpaque(true);
        }
        else if(i==4){
            jLabel4.setBackground(Color.yellow);
            jLabel4.setOpaque(true);
        }
        else if(i==5){
            jLabel5.setBackground(Color.yellow);
            jLabel5.setOpaque(true);
        }
        else if(i==6){
            jLabel6.setBackground(Color.yellow);
            jLabel6.setOpaque(true);
        }
        else if(i==7){
            jLabel7.setBackground(Color.yellow);
            jLabel7.setOpaque(true);
        }
        else if(i==8){
            jLabel8.setBackground(Color.yellow);
            jLabel8.setOpaque(true);
        }
        else if(i==9){
            jLabel9.setBackground(Color.yellow);
            jLabel9.setOpaque(true);
        }
        
    }
    public void setLableColourWhite(int i){
        
        if(i==1){
            jLabel1.setBackground(Color.white);
            jLabel1.setOpaque(true);
            System.out.println("inside jlable0");
        }
        else if(i==2){
            jLabel2.setBackground(Color.white);
            jLabel2.setOpaque(true);
        }
        else if(i==3){
            jLabel3.setBackground(Color.white);
            jLabel3.setOpaque(true);
        }
        else if(i==4){
            jLabel4.setBackground(Color.white);
            jLabel4.setOpaque(true);
        }
        else if(i==5){
            jLabel5.setBackground(Color.white);
            jLabel5.setOpaque(true);
        }
        else if(i==6){
            jLabel6.setBackground(Color.white);
            jLabel6.setOpaque(true);
        }
        else if(i==7){
            jLabel7.setBackground(Color.white);
            jLabel7.setOpaque(true);
        }
        else if(i==8){
            jLabel8.setBackground(Color.white);
            jLabel8.setOpaque(true);
        }
        else if(i==9){
            jLabel9.setBackground(Color.white);
            jLabel9.setOpaque(true);
        }
        
    }
    public void swap(){
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
